---
# tasks file for ndnping
- name: install ndnping
  apt: name=ndnping state=latest update_cache=yes

- name: create /etc/default/ndnping
  template: src=ndnping.j2 dest=/etc/default/ndnping  owner=root group=root mode="u=rw,g=r,o=r"
  notify: restart ndnping

#- copy: src=roles/ndnping/files/ndnping2.conf dest=/etc/init/ndnping2.conf owner=root group=root mode=0644

- name: start ndnping
  service: name=ndnping state=started enabled=yes

